# This script plot the result generated by profile_factorization.rs
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

table = pd.read_csv("profile_stats.csv")
table.drop(columns=["n"], inplace=True)
pollard_cols = list(k for k in table.columns if k.startswith("pollard"))
squfof_cols = list(k for k in table.columns if k.startswith("squfof"))
oneline_cols = list(k for k in table.columns if k.startswith("one_line"))

# MAXITER = 1 << 20
# table[table >= MAXITER] = np.nan

mean_table = table.groupby(table['n_bits'] // 4).agg(np.nanmean)
fig, ax = plt.subplots()
mean_table.plot("n_bits", pollard_cols, ax=ax)
mean_table.plot("n_bits", squfof_cols, ax=ax)
mean_table.plot("n_bits", oneline_cols, ax=ax)
ax.set_yscale("log")

min_table = table.groupby(table['n_bits'] // 4).agg(np.nanmin)
fig, ax = plt.subplots()
ax.plot(min_table["n_bits"], np.mean(min_table[pollard_cols], axis=1), label="pollard")
ax.plot(min_table["n_bits"], np.mean(min_table[squfof_cols], axis=1), label="squfof")
ax.plot(min_table["n_bits"], np.mean(min_table[oneline_cols], axis=1), label="one_line")
ax.legend()
ax.set_yscale("log")

plt.show()
